### ISSUE TITLE
Minor Issues for clarification

### ISSUE THREAD

**Issue by johnchurchill-DOIT** [CJuice/TransparencyPortal_PythonProcesses#2]
Hello Conrad. I've completed Step 4. Can you please clarify (in the README docs) in Step 5 which outputs are being referenced when you say "recent update data"? Is this the output in the "ProcessedData" folder? It seems likely that it is but I want to be certain.

Also a note for the question we had yesterday indicating somewhere in Step 1 or Step 2 about the locations of the Notebooks (Notebooks folder within this repo) would be helpful since the one is just in the main workspace.

**Comment by CJuice** [comment]
@johnchurchill-DOIT 
readme now states "most recent customer update data only"

Check the output location of the previous scripts that ran and made product
`output_result_csv = fr"{myvars.processed_data_folder}/{today_str}_{data_category}_PROCESSED.csv"
`

Revisions on locations of notebooks added

Note on seeing the readme section on extra required files has also been added in Step 4
